# version: 2

# sources:
#   - name: jaffle_shop
#     description: This is a replica of the Postgres database used by our app
#     database: raw
#     schema: jaffle_shop
#     freshness: # default freshness
#       # changed to config in v1.9
#       warn_after: { count: 24, period: hour }
#       error_after: { count: 2, period: day }
#     loaded_at_field: _etl_loaded_at
#     tables:
#       - name: customers
#         description: One record per customer.
#         freshness: null
#       - name: orders

  # - name: stripe
  #   description: stripe raw source
  #   database: raw
  #   schema: stripe
  #   tables:
  #     - name: payment
